version: "3.0"

services:
  master:
    image: redis:3
  slave:
    image: redis:3
    command: redis-server --slaveof master 6379
  sentinel:
    build: sentinel
    environment:
     - SENTINEL_DOWN_AFTER=5000
     - SENTINEL_FAILOVER=5000
  python:
    build: .
